### ISSUE TITLE
How did you obtain the pretrained AMR parsing model?

### ISSUE THREAD

**Issue by seanswyi** [zhangzx-uiuc/AMR-IE#3]
I checked [this GitHub Issue](https://github.com/IBM/transition-amr-parser/issues/5) on the AMR parsing GitHub that you used and apparently they haven't made their pretrained model public.

Did you separately train your own AMR model using the AMR data?

**Comment by zhangzx-uiuc** [comment]
Yes. We used IBM's code and retrained the AMR parser using AMR 3.0 data (LDC2019E81).

**Comment by LucyFann** [comment]
From your released AMR parsing checkpoint, it gets the index of AMR node and edge in the raw sentence.    
How to get these index?
